# exonerate分块
#conda activate predict
exonerate --model protein2genome --ryo '#PIS\t%pi\t%ps\t%qal\t%ql\n' --score 800 --saturatethreshold 100 --dnahspthreshold 60 --dnawordlen 14 --forwardcoordinates FALSE --softmasktarget TRUE --showtargetgff TRUE --showquerygff FALSE --showalignment FALSE --showvulgar FALSE --showcigar FALSE /ifs1/User/pengjx/database/uniprot_plant/protein.fa  58S.genome.fa --querychunkid 1 --querychunktotal 10 >out1 &
exonerate --model protein2genome --ryo '#PIS\t%pi\t%ps\t%qal\t%ql\n' --score 800 --saturatethreshold 100 --dnahspthreshold 60 --dnawordlen 14 --forwardcoordinates FALSE --softmasktarget TRUE --showtargetgff TRUE --showquerygff FALSE --showalignment FALSE --showvulgar FALSE --showcigar FALSE /ifs1/User/pengjx/database/uniprot_plant/protein.fa  58S.genome.fa --querychunkid 2 --querychunktotal 10 >out2 &
exonerate --model protein2genome --ryo '#PIS\t%pi\t%ps\t%qal\t%ql\n' --score 800 --saturatethreshold 100 --dnahspthreshold 60 --dnawordlen 14 --forwardcoordinates FALSE --softmasktarget TRUE --showtargetgff TRUE --showquerygff FALSE --showalignment FALSE --showvulgar FALSE --showcigar FALSE /ifs1/User/pengjx/database/uniprot_plant/protein.fa  58S.genome.fa --querychunkid 3 --querychunktotal 10 >out3 &
#exonerate --model protein2genome --ryo '#PIS\t%pi\t%ps\t%qal\t%ql\n' --score 800 --saturatethreshold 100 --dnahspthreshold 60 --dnawordlen 14 --forwardcoordinates FALSE --softmasktarget TRUE --showtargetgff TRUE --showquerygff FALSE --showalignment FALSE --showvulgar FALSE --showcigar FALSE /ifs1/User/pengjx/database/uniprot_plant/protein.fa  58S.genome.fa --querychunkid 4 --querychunktotal 10 >out4
#exonerate --model protein2genome --ryo '#PIS\t%pi\t%ps\t%qal\t%ql\n' --score 800 --saturatethreshold 100 --dnahspthreshold 60 --dnawordlen 14 --forwardcoordinates FALSE --softmasktarget TRUE --showtargetgff TRUE --showquerygff FALSE --showalignment FALSE --showvulgar FALSE --showcigar FALSE /ifs1/User/pengjx/database/uniprot_plant/protein.fa  58S.genome.fa --querychunkid 5 --querychunktotal 10 >out5
#exonerate --model protein2genome --ryo '#PIS\t%pi\t%ps\t%qal\t%ql\n' --score 800 --saturatethreshold 100 --dnahspthreshold 60 --dnawordlen 14 --forwardcoordinates FALSE --softmasktarget TRUE --showtargetgff TRUE --showquerygff FALSE --showalignment FALSE --showvulgar FALSE --showcigar FALSE /ifs1/User/pengjx/database/uniprot_plant/protein.fa  58S.genome.fa --querychunkid 6 --querychunktotal 10 >out6
#exonerate --model protein2genome --ryo '#PIS\t%pi\t%ps\t%qal\t%ql\n' --score 800 --saturatethreshold 100 --dnahspthreshold 60 --dnawordlen 14 --forwardcoordinates FALSE --softmasktarget TRUE --showtargetgff TRUE --showquerygff FALSE --showalignment FALSE --showvulgar FALSE --showcigar FALSE /ifs1/User/pengjx/database/uniprot_plant/protein.fa  58S.genome.fa --querychunkid 7 --querychunktotal 10 >out7
#exonerate --model protein2genome --ryo '#PIS\t%pi\t%ps\t%qal\t%ql\n' --score 800 --saturatethreshold 100 --dnahspthreshold 60 --dnawordlen 14 --forwardcoordinates FALSE --softmasktarget TRUE --showtargetgff TRUE --showquerygff FALSE --showalignment FALSE --showvulgar FALSE --showcigar FALSE /ifs1/User/pengjx/database/uniprot_plant/protein.fa  58S.genome.fa --querychunkid 8 --querychunktotal 10 >out8
#exonerate --model protein2genome --ryo '#PIS\t%pi\t%ps\t%qal\t%ql\n' --score 800 --saturatethreshold 100 --dnahspthreshold 60 --dnawordlen 14 --forwardcoordinates FALSE --softmasktarget TRUE --showtargetgff TRUE --showquerygff FALSE --showalignment FALSE --showvulgar FALSE --showcigar FALSE /ifs1/User/pengjx/database/uniprot_plant/protein.fa  58S.genome.fa --querychunkid 9 --querychunktotal 10 >out9
#exonerate --model protein2genome --ryo '#PIS\t%pi\t%ps\t%qal\t%ql\n' --score 800 --saturatethreshold 100 --dnahspthreshold 60 --dnawordlen 14 --forwardcoordinates FALSE --softmasktarget TRUE --showtargetgff TRUE --showquerygff FALSE --showalignment FALSE --showvulgar FALSE --showcigar FALSE /ifs1/User/pengjx/database/uniprot_plant/protein.fa  58S.genome.fa --querychunkid 10 --querychunktotal 10 >out10
##perl /ifs1/User/pengjx/biosoft/EVidenceModeler-master/EvmUtils/misc/Exonerate_to_evm_gff3.pl 58S_plant_protein.exonerate >test_out.gff 
