nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I R900-1P-1.split.bam  -O R900-1P-1.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I R900-1P-2.split.bam  -O R900-1P-2.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I R900-1P-3.split.bam  -O R900-1P-3.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I R900-5P-1.split.bam  -O R900-5P-1.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I R900-5P-2.split.bam  -O R900-5P-2.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I R900-5P-3.split.bam  -O R900-5P-3.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I R900-L1.split.bam  -O R900-L1.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I R900-L2.split.bam  -O R900-L2.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I R900-L3.split.bam  -O R900-L3.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I R900-S1.split.bam  -O R900-S1.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I R900-S2.split.bam  -O R900-S2.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I R900-S3.split.bam  -O R900-S3.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y58S-1P-1.split.bam  -O Y58S-1P-1.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y58S-1P-2.split.bam  -O Y58S-1P-2.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y58S-1P-3.split.bam  -O Y58S-1P-3.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y58S-5P-1.split.bam  -O Y58S-5P-1.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y58S-5P-2.split.bam  -O Y58S-5P-2.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y58S-5P-3.split.bam  -O Y58S-5P-3.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y58S-L1.split.bam  -O Y58S-L1.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y58S-L2.split.bam  -O Y58S-L2.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y58S-L3.split.bam  -O Y58S-L3.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y58S-S1.split.bam  -O Y58S-S1.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y58S-S2.split.bam  -O Y58S-S2.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y58S-S3.split.bam  -O Y58S-S3.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y900-1P-1.split.bam  -O Y900-1P-1.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y900-1P-2.split.bam  -O Y900-1P-2.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y900-1P-3.split.bam  -O Y900-1P-3.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y900-5P-1.split.bam  -O Y900-5P-1.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y900-5P-2.split.bam  -O Y900-5P-2.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y900-5P-3.split.bam  -O Y900-5P-3.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y900-L1.split.bam  -O Y900-L1.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y900-L2.split.bam  -O Y900-L2.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y900-L3.split.bam  -O Y900-L3.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y900-S1.split.bam  -O Y900-S1.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y900-S2.split.bam  -O Y900-S2.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
nohup gatk HaplotypeCaller -R ../0.genome/genome.fa -I Y900-S3.split.bam  -O Y900-S3.vcf.gz -dont-use-soft-clipped-bases --standard-min-confidence-threshold-for-calling 20 -ERC GVCF &  
