sort */DGpp.txt |uniq |wc -l
sort */DGhp.txt |uniq |wc -l
sort */Y900.R900.txt |uniq |wc -l
sort */Y900.Y58S.txt |uniq |wc -l
sort */DGhpu.txt |uniq |wc -l
sort */DGo.txt |uniq |wc -l
sort */PDO.txt |uniq |wc -l
sort */DO.txt |uniq |wc -l
sort */ODO.txt |uniq |wc -l
sort */H2P.txt |uniq |wc -l
sort */CHP.txt |uniq |wc -l
sort */B2P.txt |uniq |wc -l
sort */CLP.txt |uniq |wc -l
sort */L2P.txt |uniq |wc -l
sort */P1.txt |uniq |wc -l
sort */P2.txt |uniq |wc -l
sort */P3.txt |uniq |wc -l
sort */P4.txt |uniq |wc -l
sort */P5.txt |uniq |wc -l
sort */P6.txt |uniq |wc -l
sort */P7.txt |uniq |wc -l
sort */P8.txt |uniq |wc -l
sort */P9.txt |uniq |wc -l
sort */P10.txt |uniq |wc -l
sort */P11.txt |uniq |wc -l
sort */P12.txt |uniq |wc -l
sort */Other.txt |uniq |wc -l
